from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    class Role(models.TextChoices):
        ADMIN = 'admin', 'Admin'
        USER = 'user', 'User'
        
    class Occupation(models.TextChoices):
        ASSISTANT_GENERAL_MANAGER = 'assistant_general_manager', 'Assistant General Manager'
        ASSISTANT_MANAGER = 'assistant_manager', 'Assistant Manager'
        CLEANING_SERVICE = 'cleaning_service', 'Cleaning Service'
        DEPUTY_DIRECTOR = 'deputy_director', 'Deputy Director'
        DIRECTOR = 'director', 'Director'
        DRIVER = 'driver', 'Driver'
        FOREMAN = 'foreman', 'Foreman'
        GENERAL_FOREMAN = 'general_foreman', 'General Foreman'
        GENERAL_MANAGER = 'general_manager', 'General Manager'
        LEADER = 'leader', 'Leader'
        MANAGER = 'manager', 'Manager'
        OPERATOR = 'operator', 'Operator'
        SENIOR_MANAGER = 'senior_manager', 'Senior Manager'
        STAFF = 'staff', 'Staff'
        SUPERVISOR = 'supervisor', 'Supervisor'


    class Department(models.TextChoices):
        ACCOUNTING = 'accounting', 'Accounting'
        BUSINESS_PLAN = 'business_plan', 'Business Plan'
        CRANK_SHAFT_PRODUCTION = 'crank_shaft_production', 'Crank Shaft Production - GED #5'
        DIE_CASTING_WHEEL_GED_2 = 'die_casting_wheel_ged_2', 'Die Casting Wheel - Gedung #2'
        GENERAL_AFFAIRS = 'general_affairs', 'General Affairs'
        GEAR_AXLE_PRODUCTION = 'gear_axle_production', 'Gear Axle Production - GED #4'
        GRAVITY_DIE_CASTING_WHEEL_GD_6 = 'gravity_die_casting_wheel_gd_6', 'Gravity & Die Casting Wheel - GD #6'
        HEAD_CYLINDER_PISTON_PRODUCTION_GED_3 = 'head_cylinder_piston_production_ged_3', 'Head Cylinder & Piston Production - GED #3'
        HR_ADMINISTRATION = 'hr_administration', 'Human Resources Administration'
        INVENTORY_CONTROL = 'inventory_control', 'Inventory Control'
        MACHINING_PAINTING_WHEEL_GED_1 = 'machining_painting_wheel_ged_1', 'Machining & Painting Wheel - Gedung #1'
        MANAGEMENT_INFORMATION_SYSTEM = 'management_information_system', 'Management Information System'
        MTC_ENGINEERING = 'mtc_engineering', 'MTC Engineering'
        MTC_OPERATION = 'mtc_operation', 'MTC Operation'
        PLANT_2_PRODUCTION = 'plant_2_production', 'Plant-2 Production'
        PROD_PREPARATION_ALUMINIUM = 'prod_preparation_aluminium', 'Prod Preparation Aluminium'
        PROD_PREPARATION_STEEL = 'prod_preparation_steel', 'Prod Preparation Steel'
        PRODUCTION_COMMON = 'production_common', 'Production Common'
        PRODUCTION_DELIVERY_CONTROL = 'production_delivery_control', 'Production & Delivery Control'
        PRODUCTION_ENGINEERING_ALUMINIUM_1 = 'production_engineering_aluminium_1', 'Production Engineering Aluminium #1'
        PRODUCTION_ENGINEERING_ALUMINIUM_2 = 'production_engineering_aluminium_2', 'Production Engineering Aluminium #2'
        PRODUCTION_ENGINEERING_STEEL_1 = 'production_engineering_steel_1', 'Production Engineering Steel #1'
        PRODUCTION_ENGINEERING_STEEL_2 = 'production_engineering_steel_2', 'Production Engineering Steel #2'
        PRODUCTION_PLANNING = 'production_planning', 'Production Planning'
        PURCHASING = 'purchasing', 'Purchasing'
        QUALITY_ASSURANCE = 'quality_assurance', 'Quality Assurance'
        QUALITY_CONTROL = 'quality_control', 'Quality Control'
        QUALITY_ENGINEERING = 'quality_engineering', 'Quality Engineering'
        QSE = 'quality_safety_environment', 'Quality, Safety & Environment (QSE)'
        RECRUITMENT_TRAINING_DEVELOPMENT = 'recruitment_training_development', 'Recruitment & Training Development'
        TOOLS_CENTER = 'tools_center', 'Tools Center'
        VALUE_INNOVATION = 'value_innovation', 'Value Innovation'
        OTHER = 'other', 'Other'  

    class Section(models.TextChoices):
        ASSEMBLY = 'assembly', 'Assembly'
        BIG_ENGINE_HC_FINAL_INSPECTION = 'big_engine_hc_final_inspection', 'Big Engine & HC Final Inspection'
        CASTING_MACHINING_HC = 'casting_machining_hc', 'Casting & Machining HC'
        CN_ADMINISTRATION = 'cn_administration', 'CN Administration'
        COST_CONTROL = 'cost_control', 'Cost Control'
        COSTING_BUDGETING = 'costing_budgeting', 'Costing & Budgeting'
        CRANK_PE = 'crank_pe', 'Crank PE'
        CRANK_PE_2 = 'crank_pe_2', 'Crank PE'
        CRANK_SHAFT_MACHINING = 'crank_shaft_machining', 'Crank Shaft Machining'
        CUSTOM_CLEARANCE = 'custom_clearance', 'Custom Clearance'
        CUSTOMER_RELATIONSHIP = 'customer_relationship', 'Customer Relationship'
        DELIVERY_CONTROL = 'delivery_control', 'Delivery Control'
        DELIVERY_CONTROL_PLANT_2 = 'delivery_control_plant_2', 'Delivery Control - Plant 2'
        DIE_CASTING_WHEEL_GED_2 = 'die_casting_wheel_ged_2', 'Die Casting Wheel - Gedung #2'
        DIE_CASTING_WHEEL_GED_6 = 'die_casting_wheel_ged_6', 'Die Casting Wheel - Gedung #6'
        DIRECT_INVENTORY_CONTROL = 'direct_inventory_control', 'Direct Inventory Control'
        EQUIPMENT_CONTROL = 'equipment_control', 'Equipment Control'
        FA_CONTROL = 'fa_control', 'FA Control'
        FORK_CAM_SHIFT_HT = 'fork_cam_shift_ht', 'Fork Cam Shift H/T'
        FORGING = 'forging', 'Forging'
        FORGING_HEAT_TREATMENT_GA_PE = 'forging_heat_treatment_ga_pe', 'Forging, Heat Treatment G&A PE'
        GENERAL_ACCOUNTING = 'general_accounting', 'General Accounting'
        GENERAL_AFFAIRS = 'general_affairs', 'General Affairs'
        GENBA_CONTROL_SYSTEM = 'genba_control_system', 'Genba Control System (GCS)'
        GEAR_MACHINING = 'gear_machining', 'Gear Machining'
        GRAVITY_WHEEL_GED_6 = 'gravity_wheel_ged_6', 'Gravity Wheel - Gedung #6'
        HEAT_TREATMENT = 'heat_treatment', 'Heat Treatment'
        HIGH_PRESSURE_DIE_CASTING_PE = 'high_pressure_die_casting_pe', 'High Pressure Die Casting PE'
        HC_MACHINING_PE = 'hc_machining_pe', 'H/C Machining PE'
        INDIRECT_INVENTORY_CONTROL = 'indirect_inventory_control', 'Indirect Inventory Control'
        INDUSTRIAL_RELATIONS_HR_ADMINISTRATION = 'industrial_relations_hr_administration', 'Industrial Relations & HR Administration'
        INVENTORY_OPERATION_CONTROL = 'inventory_operation_control', 'Inventory Operation Control'
        IOT = 'iot', 'IoT'
        LEGAL_RISK_MANAGEMENT = 'legal_risk_management', 'Legal & Risk Management'
        LOGISTIC_CONTROL = 'logistic_control', 'Logistic Control'
        LOW_PRESSURE_DIE_CASTING_GRAVITY_PE = 'low_pressure_die_casting_gravity_pe', 'Low Pressure Die Casting & Gravity PE'
        MACHINING_GA_PE = 'machining_ga_pe', 'Machining G&A PE'
        MACHINING_PAINTING_WHEEL_GED_1 = 'machining_painting_wheel_ged_1', 'Machining & Painting Wheel - Gedung #1'
        MACHINING_WHEEL_PE = 'machining_wheel_pe', 'Machining Wheel PE'
        MANAGEMENT_INFORMATION_SYSTEM = 'management_information_system', 'Management Information System'
        MANUFACTURING_CENTER = 'manufacturing_center', 'Manufacturing Center'
        MEDICAL_WELFARE = 'medical_welfare', 'Medical & Welfare'
        MOLD_DIES_MANUFACTURING = 'mold_dies_manufacturing', 'Mold & Dies Manufacturing'
        MOLD_DIES_MAINTENANCE = 'mold_dies_maintenance', 'Mold & Dies Maintenance'
        MTC_ENGINEERING_ALUMINIUM = 'mtc_engineering_aluminium', 'MTC Engineering Aluminium'
        MTC_ENGINEERING_STEEL = 'mtc_engineering_steel', 'MTC Engineering Steel'
        MTC_ENGINEERING_UTILITY = 'mtc_engineering_utility', 'MTC Engineering Utility'
        MTC_OPERATION_1 = 'mtc_operation_1', 'MTC Operation 1'
        MTC_OPERATION_2 = 'mtc_operation_2', 'MTC Operation 2'
        MTC_OPERATION_3 = 'mtc_operation_3', 'MTC Operation 3'
        MTC_OPERATION_UTILITY = 'mtc_operation_utility', 'MTC Operation Utility'
        PIN_WEIGHT_CAM_SHAFT_MACHINING = 'pin_weight_cam_shaft_machining', 'Pin, Weight & Cam Shaft Machining'
        PISTON_FORGING_MACHINING_PLATTING = 'piston_forging_machining_platting', 'Piston Forging, Machining & Plating'
        PISTON_PE = 'piston_pe', 'Piston PE'
        POC_WHEEL = 'poc_wheel', 'POC Wheel'
        PROCESS_CONTROL = 'process_control', 'Process Control'
        PROD_PREPARATION_ALUMINIUM = 'prod_preparation_aluminium', 'Prod Preparation Aluminium'
        PROD_PREPARATION_STEEL = 'prod_preparation_steel', 'Prod Preparation Steel'
        PRODUCTION_CONTROL = 'production_control', 'Production Control'
        PRODUCTION_CONTROL_PLANT_2 = 'production_control_plant_2', 'Production Control - Plant 2'
        PRODUCTION_PLANNING_SYSTEM = 'production_planning_system', 'Production Planning & System'
        PURCHASE_ADMINISTRATION = 'purchase_administration', 'Purchase Administration'
        PURCHASE_STRATEGY = 'purchase_strategy', 'Purchase Strategy'
        QUALITY_CONTROL_1 = 'quality_control_1', 'Quality Control 1'
        QUALITY_CONTROL_2 = 'quality_control_2', 'Quality Control 2'
        QUALITY_CONTROL_3 = 'quality_control_3', 'Quality Control 3'
        QUALITY_ENGINEERING_ALUMINIUM = 'quality_engineering_aluminium', 'Quality Engineering Aluminium'
        QUALITY_ENGINEERING_STEEL = 'quality_engineering_steel', 'Quality Engineering Steel'
        QUALITY_MANAGEMENT_SYSTEM = 'quality_management_system', 'Quality Management System'
        QUALITY_SYSTEM_CALIBRATION = 'quality_system_calibration', 'Quality System & Calibration'
        RECRUITMENT_SELECTION = 'recruitment_selection', 'Recruitment & Selection'
        SAFETY_ENVIRONMENT = 'safety_environment', 'Safety & Environment'
        SHAFT_PARTS_PE = 'shaft_parts_pe', 'Shaft Parts PE'
        SUPPLIERS_RELATIONSHIP = 'suppliers_relationship', 'Suppliers Relationship'
        TAXATION = 'taxation', 'Taxation'
        TECHNICAL_SUPPORT_DOCUMENTATION = 'technical_support_documentation', 'Technical Support & Documentation'
        TOOLS_JIG_MAINTENANCE = 'tools_jig_maintenance', 'Tools & Jig Maintenance'
        TRAINING_DEVELOPMENT = 'training_development', 'Training & Development'
        TREASURY = 'treasury', 'Treasury'
        WORKSHOP_CENTER = 'workshop_center', 'Workshop Center'
        OTHER = 'other', 'Other'  



    base_role = Role.USER
    role = models.CharField(max_length=20, choices=Role.choices, default=base_role)
    occupation = models.CharField(max_length=55, choices=Occupation.choices, default=Occupation.STAFF)
    department = models.CharField(max_length=55, choices=Department.choices, default=Department.OTHER)
    section = models.CharField(max_length=55, choices=Section.choices, default=Section.OTHER)
    nik = models.CharField(max_length=50, unique=True, blank=False, null=False)
    cc = models.CharField(max_length=5, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.role = self.base_role
        return super().save(*args, **kwargs)
